#!/bin/bash

compilemain=0
compileunittest=0
execute=0

while getopts ?hmue opts
do
	case $opts in
		\?|h)
			echo "HELP"
			echo "?|h	HELP"
			echo "m		MAIN"
			echo "u		UNITTEST"
			echo "e		EXECUTE"
			;;
		m)
			compilemain=1
			;;
		u)
			compileunittest=1
			;;
		e)	
			execute=1
			;;
	esac
done

if [ $compilemain == 1 ]
then
	g++ main.cpp ../4001-ROM/4001.cpp ../4002-RAM/4002.cpp ../4004/4004.cpp ../4004/4004_stack.cpp ../inc/intelhex.c -o /tmp/main.out
fi

if [ $compileunittest == 1 ]
then
	g++ unittest.cpp ../4001-ROM/4001.cpp ../4002-RAM/4002.cpp ../4004/4004.cpp ../4004/4004_stack.cpp ../inc/intelhex.c -o /tmp/unittest.out
fi

if [ $execute == 1 ]
then
	if [ $compilemain == 1 ]
	then
		/tmp/main.out
	elif [ $compileunittest == 1 ]
	then
		/tmp/unittest.out
	fi
fi
